@startuml ActitvityDiagramm
|Администратор|

|Преподаватель|
start
:Сформировать учебный план;
:Составить заявку на создание курса;

|Администратор|
:Рассмотреть заявку на создание курса;
if (Данные заполнены корректно?) then (да)

|Преподаватель|
:Курс создан;
else (нет)
:Заявка удалена;
detach
endif
:Открыть запись;

|Покупатель|

:Найти курс;
:Выбрать курс;
:Записаться;
if (На счету достаточно средств?) then (да)
:Получить информацию по email;
else (нет)
:Оплата отменена;
:Место свободно для записи;
detach
endif

stop
@enduml
