@startuml C4-Context

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Context

Person(Student, "Студент [Пользователь]", "Прохождение курсов, сдача тестов, получение сертификатов")

Person(Administrator, "Администратор [Пользователь]", "Управление курсами, пользователями, доступами, статистикой по курсам")

Person(Teacher, "Преподаватель [Пользователь]", "Создание и редактивирование курсов, мониторинг успеваемости, предоставление обратной связи")

Person(TechSup, "Тех. поддержка [Пользователь]", "Сопровождение системы, устранение угроз, масштабирование системы")

System(App, "E-learning [Программная система]", "Платформа для обучения оналйн, предоставление инструментов для создания и редактирования курсов")

System_Ext(ObrNadzor, "ОбрНадзор API [Программная система]", "Проверка аккредитации преподавателя")

System_Ext(Email, "Cистема электронной почты [Программная система]", "Поставщик системы отправки электронной почты")

System_Ext(PaymentSystem, "Электронная платежная система [Программная система]", "Интернет-эквайринг, прием платежей")


Rel(Student, App, "Обучение")
Rel(Administrator, App, "Модерация")
Rel(Teacher, App, "Преподавание")
Rel(TechSup, App, "Сопровождение")

Rel(App, ObrNadzor, "Проверка преподавателя")
Rel(App, Email, "Отправка писем")
Rel(App, PaymentSystem, "Оплата")

@enduml
